config/routes.rb
Rails.application.routes.draw do
  get 'anders/index'
  root 'home#show'
  resources :home do
    collection do
      get :details
      post :fill
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ander.rb
class Ander < ApplicationRecord
  after_create_commit :create_stream
  after_destroy_commit :destroy_stream

  def toggle_connection
    self.update(connected: !connected)
    update_stream
  end

  private

  def update_stream
    broadcast_replace_later_to 'anders'
  end

  def create_stream
    broadcast_prepend_later_to 'anders'
  end

  def destroy_stream
    broadcast_remove_to 'anders'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/anders_controller.rb
class AndersController < ApplicationController
  def index
    # sleep 3
    @anders = Ander.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def fill
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.append('filler', partial: 'filler', locals: { time: Time.now })
      end
    end
  end
end

app/helpers/anders_helper.rb
module AndersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/anders/_ander.html.slim
= turbo_frame_tag dom_id(ander), data: { controller: "display"} do
  div data-display-target="element"  data-filter-target="house" data-houses="#{ander.houses}" style="border: 1px red solid;"
    p = ander.name
    p #{ander.houses} houses
    p Connected: #{ander.connected ? 'Yes' : 'No'}
  button data-action="display#toggle" click me and I'll disappear!

app/views/anders/index.html.slim
= turbo_frame_tag 'anders' do
  div data-controller="filter"
    = render @anders
    div
      input type="number" data-filter-target='number' value="10"
    div style="display: flex;"
      button data-action="filter#filter_bigger" filter bigger
      button data-action="filter#filter_smaller" filter smaller

    = link_to 'Really Go home', root_path, data: {"turbo-frame" => '_top'}

p THis is in the index but outside turbo fram

app/views/home/_filler.html.slim
= turbo_frame_tag "filler_#{time}" do
  div style="border: 1px solid black"
    p I will append to the empty content.
    p It is now: #{time}

app/views/home/details.html.slim
= turbo_frame_tag 'anders' do
  h2 I will show the block
  p I give you details about the stuff you clicked
  div
    = link_to 'Show me anders again', anders_index_path
  div
    = link_to 'Fill bellow', fill_home_index_path, method: :post

  = turbo_stream_from 'filler'
  = turbo_frame_tag 'filler' do
    p


p But this will not be shown
= link_to 'Really Go home', root_path

app/views/home/show.html.slim
= turbo_frame_tag 'title', target: 'anders' do
  / #
  h1 here I am
  = link_to 'click me (through the server)', details_home_index_path
  / # data: { "turbo-frame" => 'anders'}
  button data-controller="navigate not_navigate" data-action="navigate#details" Click me (through js)
/ div.full-red-block

= turbo_stream_from 'anders'
= turbo_frame_tag 'anders', src: anders_index_path, loading: 'lazy' do
  div style="height: 500px; border: 1px red solid"
    p I am filler content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwirePllayin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>